language: groovy
jdk:
  - openjdk11
before_install:
 - chmod +x gradlew
script: ./gradlew clean build functionalTest
notifications:
  email: false
branches:
  only:
    - master
env:
  global:
  - TERM=dumb
